-- 对话日志表 - 记录完整的对话信息，便于问题排查和日志分析
CREATE TABLE IF NOT EXISTS conversation_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL COMMENT '用户ID',
    session_id VARCHAR(64) NOT NULL COMMENT '会话ID',
    trace_id VARCHAR(64) COMMENT '追踪ID',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '对话创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '对话更新时间',
    response_duration_seconds DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '响应时长（秒）',
    llm_rounds INT NOT NULL DEFAULT 0 COMMENT 'LLM响应执行轮数',
    tool_call_rounds INT NOT NULL DEFAULT 0 COMMENT '工具调用轮数',
    is_exceed_max_round TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否超出最大轮',
    is_success TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否成功执行',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态',
    finish_reason VARCHAR(128) COMMENT '结束原因',
    llm_model VARCHAR(128) COMMENT '使用的LLM模型',
    skill_name VARCHAR(128) COMMENT '调用的技能名称',
    tool_name VARCHAR(128) COMMENT '调用的工具名称',
    log_level VARCHAR(32) COMMENT '日志级别',
    log_message TEXT COMMENT '日志消息内容',
    error_message TEXT COMMENT '错误信息',
    error_stack_trace LONGTEXT COMMENT '错误堆栈信息',
    request_data LONGTEXT COMMENT '请求数据(JSON格式)',
    response_data LONGTEXT COMMENT '响应数据(JSON格式)',
    conversation_content LONGTEXT COMMENT '对话内容(JSON格式)',
    total_tokens INT COMMENT '消耗的token总数',
    prompt_tokens INT COMMENT '提示词token数',
    completion_tokens INT COMMENT '补全token数',
    agent_version VARCHAR(32) COMMENT '代理版本',
    environment VARCHAR(32) COMMENT '环境',
    INDEX idx_user_id (user_id),
    INDEX idx_session_id (session_id),
    INDEX idx_trace_id (trace_id),
    INDEX idx_created_at (created_at),
    INDEX idx_status (status),
    INDEX idx_is_success (is_success)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='对话日志表';